#! /bin/bash

echo -n "Enter input file name: "
read input

test -f $input
if (($? != 0))
then echo -n "File '$input' does not exist."
echo ""
exit 0
fi

test -w $input
if (($? != 0))
then echo -n "File '$input' is not writable."
echo ""
exit 0
fi

test -r $input
if (($? != 0))
then echo -n "File '$input' is not readable."
echo ""
exit 0
fi

echo -n "Enter output file name: "
read output

test -f $output
if (($? != 0))
then echo -n "File '$output' does not exist."
echo ""
exit 0
fi

test -w $output
if (($? != 0))
then echo -n "File '$output' is not writable."
echo ""
exit 0
fi

test -f $output
if (($? == 0))
then
test -w $output
if (($? == 0))
then
echo -n "File '$output' exists."
echo
fi
fi

echo -n "Append to it (y/n)? "
read ans

while test $ans != y -a $ans != Y -a $ans != N -a $ans != n
do
echo -n "Invalid option"
echo
echo -n "Append to it (y/n)? "
read ans
done

if test $ans == y -o $ans == Y
then

num=1
while read -r line
do
echo $num: $line >> $output
((num++))
done < $input

elif test $ans == n -o $ans == N
then 
exit 0
fi
